trigger:
- master

jobs:
  - job:
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'
    displayName: Build and test $(imageName)
    steps:
    - task: 'DotNetCoreCLI@2'
      inputs:
        command: test
